# Autogenerated wrapper script for oneAPI_Level_Zero_Headers_jll for x86_64-linux-gnu
export ze_api

JLLWrappers.@generate_wrapper_header("oneAPI_Level_Zero_Headers")
JLLWrappers.@declare_file_product(ze_api)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        ze_api,
        "include/level_zero/ze_api.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
